name: widget-server pipe DockerHub

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and export image
        id: build_export_image
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: $DOCKERHUB_REPOSITORY:test

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '$DOCKERHUB_REPOSITORY:test'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and push image to DockerHub
        id: build_push_image
        cache-from: type=gha
        env:
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to DockerHub"
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
          echo "Image pushed successfully"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
