name: widget-server pipe DockerHub

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTUPUT

      - name: Build and push the image to DockerHub
        id: build_push_image
        env:
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to DockerHub"
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
          echo "Image pushed successfully"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
